import {Inter} from 'next/font/google'
import cn from 'classnames'
import {Header} from '@/components/Header'
import {Footer} from '@/components/Footer'
import s from './layout.module.scss'
import type {Metadata} from 'next'
import './globals.css'
import 'normalize.css'

const inter = Inter({subsets: ['latin']})
export const metadata: Metadata = {
 title: 'Space | Home',
 description: 'Generated by create next app',
}
export default function RootLayout({
                                    children,
                                   }: {
 children: React.ReactNode
}) {

 return (
  <html lang='en'>
  <body className={cn(inter.className, s.container)}>
  <Header/>
  <main className={s.main}>{children}</main>
  <Footer/>
  </body>
  </html>
 )
}
