import {ReactNode} from 'react'
import {Fredoka} from 'next/font/google'
import cn from 'classnames'
import {Header} from '@/components/Header'
import {Footer} from '@/components/Footer'
import s from './layout.module.scss'
import type {Metadata} from 'next'
import '../styles/globals.css'
import '../styles/normalize.css'

const inter = Fredoka({subsets: ['latin']})
export const metadata: Metadata = {
 title: 'Space | Home',
 description: 'Generated by create next app',
}
export default function RootLayout({
                                    children,
                                   }: {
 children: ReactNode
}) {

 return (
  <html lang='en'>
  <body className={cn(inter.className, s.body)}>
  <Header/>
  <main className={s.main}>
   {children}
  </main>
  <Footer/>
  </body>
  </html>
 )
}
